version: 0.2

phases:
  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh configure-aws.sh apply-terraform.sh
      - ./install-terraform.sh
      - cd .. && echo "checking provider executable"
      - ls -l .terraform/providers/registry.terraform.io/hashicorp/aws/5.14.0/linux_amd64
      - if [ "$(stat -c %a .terraform/providers/registry.terraform.io/hashicorp/aws/5.14.0/linux_amd64/terraform-provider-aws_v5.14.0_x5)" != "755" ]; then chmod +x .terraform/providers/registry.terraform.io/hashicorp/aws/5.14.0/linux_amd64/*; fi
      
  build:
    commands:
      - ./cicd/apply-terraform.sh
  
  post_build:
    commands:
      - rm -rf .git
      - rm -rf .terraform/plugins
artifacts:
  files:
    - '**/*'
