version: 0.2

phases:
  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh configure-aws.sh apply-terraform.sh
      - ./install-terraform.sh
      # - ./configure-aws.sh
  
  build:
    commands:
      - echo "checking provider executable"
      - ls -l .terraform/providers/registry.terraform.io/hashicorp/aws/5.14.0/linux_amd64
      - terraform init
      - ./cicd/apply-terraform.sh
  
  post_build:
    commands:
      - rm -rf .git
      - rm -rf .terraform/plugins
artifacts:
  files:
    - '**/*'