version: 0.2
env:
  secrets-manager:
    TF_VAR_EXTERNAL_ID: "CodeBuild.AwsHarisSandbox.TerraformManagement.ExternalId:external_id"
    TF_VAR_ROLE_ARN: "CodeBuild.AwsHarisSandbox.TerraformManagement.ExternalId:role_arn"
phases:
  pre_build:
    commands:
      - cd cicd
      - chmod +x install-terraform.sh configure-aws.sh plan-terraform.sh
      - ./install-terraform.sh
  build:
    commands:
      - cd ..
      - ./cicd/plan-terraform.sh
  
  post_build:
    commands:
      - rm -rf .git
      - rm -rf .terraform/plugins
artifacts:
  files:
    - '**/*'
    